services:
  - type: web
    name: web-audit-ai-backend
    env: docker # Changed from node to docker
    plan: free
    region: singapore
    rootDir: backend
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromValue: YOUR_MONGODB_URI_HERE
      - key: GEMINI_API_KEY
        fromValue: YOUR_GEMINI_API_KEY_HERE
      - key: GROQ_API_KEY
        fromValue: YOUR_GROQ_API_KEY_HERE
